### ISSUE TITLE
Metamask RPC Error

### ISSUE THREAD

**Issue by fredfortier** [kangarang/tcr-ui#101]
I follow the steps as closely as I could. I deployed the contracts and I can see my token in Metamask. However, I get an error when loading the page. I tried resetting my Metamask account, switching between networks, etc. Any pointers would be appreciated.

![screenshot 2018-06-01 16 59 28](https://user-images.githubusercontent.com/1474114/40867983-750d82c0-65bd-11e8-9d07-6f6f35f25d7b.png)
![screenshot 2018-06-01 17 02 10](https://user-images.githubusercontent.com/1474114/40867996-8a99a6f0-65bd-11e8-9980-e3480637da5b.png)

```
$ truffle networks

The following networks are configured to match any network id ('*'):

    coverage
    ganache
    rinkeby

Closely inspect the deployed networks below, and use `truffle networks --clean` to remove any networks that don't match your configuration. You should not use the wildcard configuration ('*') for staging and production networks for which you intend to deploy your application.

Network: UNKNOWN (id: 420)
  AttributeStore: 0x8e6d692b08160d75570806abca53f5a6c3ee172b
  DLL: 0xd05619025704938c95beecf7db082b34a75c6c4c
  EIP20: 0x63fa3d368b4f6829eb63f265470cd588c99ed605
  Migrations: 0xf64c968d4b2d1a0c13432a148e962e7b376a1dd0
  PLCRVoting: 0x11121458df2af572be9c8ae1a727cfd172475306
  Parameterizer: 0x06f2d6ac7e992d0ea6d4653bf25b66a18ed280fd
  Registry: 0x20538f44f230be95a8a61e3a9287e29cc038d35d

Network: mainnet (id: 1)
  No contracts deployed.
```
I got the 420 networkId from here: `tcr-ui/src/redux/modules/home/sagas.js:33`

**Comment by kangarang** [comment]
hi @fredfortier, i'm sorry it's taken a while to respond to your issue -- i've was afk last week. have you had any luck since? i believe what your issue boiled down to was: the address of the registry was incorrect, thus none of the app loaded correctly. i updated some config files, error messages, and the quickstart section of the docs. you'll have to pull the recent changes on both this repo as well as https://github.com/kangarang/tcr. hope that's enough to get your started. lemme know how it goes!
